#!/usr/bin/env python

import numpy as np
import pickle
import sys

with open('model', 'rb') as f:
	model = pickle.load(f)

with open('labels', 'rb') as f:
	label_encoder = pickle.load(f)

def decode():
	for line in sys.stdin:
		words = [[float(c) / 9 for c in word] for word in line.split()]
		x = np.array(words)
		prediction = model.predict(x)
		letters = label_encoder.inverse_transform(prediction)
		print(''.join(letters))

if __name__ == '__main__':
	decode()
